### 使用0来使用内部错误
代码
```
 #[error("Failed to read file: {0}")]
```
测试1：
```
println!("{:?}", io_err);
```
结果1：
```
IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
测试2：
```
println!("{:?}", io_err);
```
结果2：
```
Failed to read file: No such file or directory (os error 2)
```
### 不使用内部
代码
```
#[error("Failed to read file")]
```
测试：
```
println!("{:?}", io_err);
```
结果:
```
Failed to read file
```
